dist: trusty
language: node_js
os: linux
node_js:
  - "10"

cache: npm

jobs:
  include:
		- stage: "Test"
			name: "Security test"
			script:
				- npm i -g snyk
				- snyk --help
				- snyk auth $SNYK_TOKEN
				- snyk test
				- snyk monitor
    - stage: "Build"
      name: "build lib"
      script:
        - npm run build-lib
      deploy:
      - provider: script
        script: npm run semantic-release
        on:
					branch: master
    - stage: "Release"
      if: branch = master
      script: npm run build-storybook
      deploy:
      - provider: pages
        token: $GH_TOKEN
        keep_history: true
        local_dir: dist/docs

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
